-- MySQL Script generated by MySQL Workbench
-- Fri Sep 10 20:55:49 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tiendaaldia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tiendaaldia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tiendaaldia` DEFAULT CHARACTER SET utf8 ;
USE `tiendaaldia` ;

-- -----------------------------------------------------
-- Table `tiendaaldia`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendaaldia`.`Usuarios` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `nombresUsuarios` VARCHAR(45) NOT NULL,
  `apellidosUsuarios` VARCHAR(45) NOT NULL,
  `tipoIdentificacion` VARCHAR(45) NOT NULL,
  `identificacion` VARCHAR(45) NOT NULL,
  `direccionUsuarios` VARCHAR(45) NOT NULL,
  `telefonoUsuarios` VARCHAR(45) NOT NULL,
  `correoUsuarios` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuarios`),
  UNIQUE INDEX `idusuarios_UNIQUE` (`idUsuarios` ASC) VISIBLE,
  UNIQUE INDEX `identificacion_UNIQUE` (`identificacion` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendaaldia`.`tendero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendaaldia`.`tendero` (
  `idTendero` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  `idUsuario` INT NOT NULL,
  `nombreTienda` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTendero`),
  UNIQUE INDEX `idTendero_UNIQUE` (`idTendero` ASC) VISIBLE,
  INDEX `usuarioID_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `TenderoUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `tiendaaldia`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendaaldia`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendaaldia`.`Proveedor` (
  `idProveedor` INT NOT NULL AUTO_INCREMENT,
  `nombreProveedor` VARCHAR(45) NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idProveedor`),
  UNIQUE INDEX `idProveedor_UNIQUE` (`idProveedor` ASC) VISIBLE,
  INDEX `usuarioId_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `ProveedorUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `tiendaaldia`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendaaldia`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendaaldia`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nombreCategoria` VARCHAR(45) NOT NULL,
  `decripcionCategoria` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategoria`),
  UNIQUE INDEX `idCategoria_UNIQUE` (`idCategoria` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendaaldia`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendaaldia`.`Producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `nombreProducto` VARCHAR(45) NOT NULL,
  `referenciaProducto` VARCHAR(45) NOT NULL,
  `cantidadProducto` DOUBLE NOT NULL,
  `precioCompra` DOUBLE NOT NULL,
  `precioVenta` DOUBLE NOT NULL,
  `idProveedor` INT NOT NULL,
  `idCategoria` INT NOT NULL,
  `ivaActual` DOUBLE NOT NULL,
  PRIMARY KEY (`idProducto`),
  UNIQUE INDEX `idProducto_UNIQUE` (`idProducto` ASC) VISIBLE,
  INDEX `proveedorId_idx` (`idProveedor` ASC) VISIBLE,
  INDEX `categoriaId_idx` (`idCategoria` ASC) VISIBLE,
  CONSTRAINT `ProductoProveedor`
    FOREIGN KEY (`idProveedor`)
    REFERENCES `tiendaaldia`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ProductoCategoria`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `tiendaaldia`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendaaldia`.`Transacciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendaaldia`.`Transacciones` (
  `idTransacciones` INT NOT NULL AUTO_INCREMENT,
  `idProducto` INT NOT NULL,
  `totalTransaccion` DOUBLE NOT NULL,
  `cantidadTransaccion` DOUBLE NOT NULL,
  `valorUnitarioCompra` DOUBLE NOT NULL,
  `valorUnitarioVenta` DOUBLE NOT NULL,
  `fechaTransaccion` DATE NOT NULL,
  `ivaTransaccion` DOUBLE NOT NULL,
  `tipoTransacciones` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTransacciones`),
  UNIQUE INDEX `idVentas_UNIQUE` (`idTransacciones` ASC) VISIBLE,
  INDEX `TransaccionProducto_idx` (`idProducto` ASC) VISIBLE,
  CONSTRAINT `TransaccionProducto`
    FOREIGN KEY (`idProducto`)
    REFERENCES `tiendaaldia`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
